(function () {
  const translations = {
    "Inicio":"Home", "Historia":"History", "Misión y visión":"Mission & vision", "Elenco":"Staff", "Apóyanos":"Support us", "Redes":"Socials",
    "✦ Bienvenidos a nuestra constelación ✦":"✦ Welcome to our constellation ✦",
    "Café":"Café", "Un rincón entre estrellas donde cada integrante le da vida a una experiencia única dentro de VRChat.":"A corner among the stars where every member brings a unique VRChat experience to life.",
    "✦ De una chispa a una constelación ✦":"✦ From a spark to a constellation ✦", "Nuestra historia":"Our story",
    "Antes de que Astral Moon tuviera un nombre, ya existía una luz reuniendo personas. Esta es la historia de cómo una pequeña familia encontró su lugar entre las estrellas.":"Before Astral Moon had a name, a light was already bringing people together. This is the story of how a small family found its place among the stars.",
    "La primera chispa":"The first spark", "El sueño de Mapache":"Mapache's dream",
    "Todo comenzó con Mapache, la mente y el corazón detrás de":"It all began with Mapache, the mind and heart behind",
    ". Ella imaginó un lugar donde personas distintas pudieran encontrarse, compartir su talento y sentirse parte de algo especial. Con esa idea encendió la primera luz y, poco a poco, fue reuniendo a quienes terminarían convirtiéndose en una familia.":". She imagined a place where different people could meet, share their talents and feel part of something special. With that idea, she lit the first light and gradually brought together those who would become a family.",
    "Todo comenzó con Mapache, la mente y el corazón detrás de Mapache Entertainment Café. Ella imaginó un lugar donde personas distintas pudieran encontrarse, compartir su talento y sentirse parte de algo especial. Con esa idea encendió la primera luz y, poco a poco, fue reuniendo a quienes terminarían convirtiéndose en una familia.":"It all began with Mapache, the mind and heart behind Mapache Entertainment Café. She imagined a place where different people could meet, share their talents and feel part of something special. With that idea, she lit the first light and gradually brought together those who would become a family.",
    "Maids, mayordomos, artistas, seguridad y amigos llegaron desde rincones diferentes de VRChat. Mapache no solamente creó un café: nos dio un punto de encuentro y la oportunidad de conocernos.":"Maids, butlers, artists, security members and friends arrived from different corners of VRChat. Mapache did more than create a café: she gave us a meeting place and the chance to get to know one another.",
    "La familia del café":"The café family", "Un hogar llamado Mapache Entertainment":"A home called Mapache Entertainment",
    "Cada servicio abrió las puertas a nuevas historias. Entre risas, nervios, shows, colaboraciones y noches inolvidables, el café se volvió un hogar para su elenco y su comunidad. Ahí aprendimos a trabajar juntos, a cuidarnos y a hacer brillar a los demás.":"Every service opened the door to new stories. Through laughter, nerves, shows, collaborations and unforgettable nights, the café became a home for its staff and community. There we learned to work together, care for one another and help others shine.",
    "Aunque el tiempo trajo cambios y cada persona comenzó a buscar su propio camino, la luz de aquella primera etapa nunca desapareció. Permaneció guardada en los recuerdos, los lazos y todo lo que habíamos construido juntos.":"Although time brought change and each person began to seek their own path, the light of that first chapter never disappeared. It remained in our memories, our bonds and everything we had built together.",
    "La luna encuentra su cielo":"The moon finds its sky", "El nacimiento de Astral Moon":"The birth of Astral Moon",
    "Lock tomó esa luz y la llevó hacia un nuevo cielo. Inspirado por la luna, las estrellas y el deseo de proteger la familia que se había formado, comenzó una nueva era:":"Lock took that light and carried it into a new sky. Inspired by the moon, the stars and the desire to protect the family that had formed, a new era began:",
    "Lock tomó esa luz y la llevó hacia un nuevo cielo. Inspirado por la luna, las estrellas y el deseo de proteger la familia que se había formado, comenzó una nueva era: Astral Moon Café.":"Lock took that light and carried it into a new sky. Inspired by the moon, the stars and the desire to protect the family that had formed, a new era began: Astral Moon Café.",
    "No fue el final de Mapache Entertainment, sino la transformación de su legado. La antigua chispa se convirtió en una constelación con una identidad propia: más celestial, mágica y soñadora, pero todavía unida por el mismo deseo de crear momentos especiales y ofrecer un lugar al cual pertenecer.":"It was not the end of Mapache Entertainment, but the transformation of its legacy. The old spark became a constellation with an identity of its own: more celestial, magical and dreamlike, yet still united by the same wish to create special moments and offer a place to belong.",
    "Un legado entre estrellas":"A legacy among the stars", "La constelación continúa":"The constellation continues",
    "Por haber sido quien imaginó el primer café y reunió a la familia original, Mapache recibe el título simbólico de":"For imagining the first café and bringing the original family together, Mapache receives the symbolic title of",
    ". Es nuestro homenaje a la persona que encendió la primera luz de esta historia.":". It is our tribute to the person who lit the first light of this story.",
    "Por haber sido quien imaginó el primer café y reunió a la familia original, Mapache recibe el título simbólico de Fundadora Astral. Es nuestro homenaje a la persona que encendió la primera luz de esta historia.":"For imagining the first café and bringing the original family together, Mapache receives the symbolic title of Astral Founder. It is our tribute to the person who lit the first light of this story.",
    "Hoy, cada integrante de Astral Moon es una estrella diferente. Lock guía la constelación como Señor del Cosmos, mientras el elenco mantiene vivo un legado que comenzó alrededor de una taza de café y que ahora continúa bajo la luz de la luna.":"Today, every Astral Moon member is a different star. Lock guides the constellation as Lord of the Cosmos, while the staff keeps alive a legacy that began around a cup of coffee and now continues beneath the moonlight.",
    "El rumbo de nuestra constelación":"The course of our constellation", "Nuestra esencia":"Our essence", "Misión":"Mission", "Crear momentos que brillen":"Create moments that shine",
    "Ofrecer una experiencia de entretenimiento y convivencia dentro de VRChat donde cada visitante se sienta bienvenido, escuchado y acompañado. Buscamos brindar servicios creativos, dinámicas especiales y momentos memorables en un ambiente seguro, respetuoso y lleno de magia astral.":"To offer an entertaining and welcoming VRChat experience where every visitor feels welcome, heard and accompanied. We aim to provide creative services, special activities and memorable moments in a safe, respectful atmosphere filled with astral magic.",
    "Visión":"Vision", "Ser un referente entre estrellas":"Become a guiding star",
    "Convertir a Astral Moon Café en una comunidad reconocida por su creatividad, organización y calidez; un proyecto capaz de unir talentos, impulsar a su elenco y crear experiencias innovadoras que dejen una huella positiva dentro y fuera de VRChat.":"To make Astral Moon Café a community known for its creativity, organization and warmth; a project capable of bringing talents together, supporting its staff and creating innovative experiences that leave a positive mark inside and beyond VRChat.",
    "Nuestra constelación":"Our constellation", "Conoce al elenco":"Meet the staff",
    "33 integrantes dan vida a nuestro elenco. Selecciona un nombre para abrir su perfil.":"33 members bring our staff to life. Select a name to open their profile.",
    "☾ Fundación y Dirección":"☾ Founding & Direction", "✧ Maids Lunares":"✧ Lunar Maids", "☀ Mayordomos Solares":"☀ Solar Butlers", "🌗 Elenco Mixto":"🌗 Mixed Staff", "⛨ Seguridad":"⛨ Security", "☆ Artistas":"☆ Artists", "✦ Creadores de mapa":"✦ World Creators",
    "Integrantes por anunciar.":"Members to be announced.", "Fundadora Astral · Título honorífico":"Astral Founder · Honorary title", "Director Estelar":"Stellar Director", "Director Estelar · Pilar de Astral Moon":"Stellar Director · Pillar of Astral Moon", "Maid Lunar":"Lunar Maid", "Maid Lunar · Espíritu del bosque":"Lunar Maid · Forest Spirit", "Maid Lunar · Alicornio cambiaformas":"Lunar Maid · Shapeshifting Alicorn", "Maid Lunar · Princesa de la Luna Perdida":"Lunar Maid · Princess of the Lost Moon", "Maid Lunar · Princesa Lunar Perdida":"Lunar Maid · Lost Lunar Princess", "Mayordomo Solar":"Solar Butler", "Mayordomo Solar · Viajero del hogar":"Solar Butler · Seeker of Home", "Mayordomo Solar · Portador de la suerte":"Solar Butler · Bearer of Good Fortune", "Mayordomo Solar · Guardián tanuki":"Solar Butler · Tanuki Guardian", "Maid y Mayordomo":"Maid & Butler", "Maid y Mayordomo · Semidiós dracónico":"Maid & Butler · Draconic Demigod", "Seguridad":"Security", "Seguridad · Guardián del astro":"Security · Guardian of the Star",
    "✦ Apoya nuestra constelación ✦":"✦ Support our constellation ✦", "Una taza puede encender otra estrella":"One cup can light another star",
    "En nuestro Ko-fi puedes realizar donaciones voluntarias para apoyar el crecimiento de Astral Moon Café o adquirir la suscripción VIP del café.":"On our Ko-fi, you can make a voluntary donation to support the growth of Astral Moon Café or purchase the café's VIP membership.",
    "Donaciones voluntarias":"Voluntary donations", "Ayúdanos a seguir creando experiencias, eventos y momentos especiales para nuestra comunidad.":"Help us continue creating experiences, events and special moments for our community.",
    "Suscripción VIP":"VIP Membership", "Conoce y adquiere la membresía VIP de Astral Moon Café directamente en Ko-fi.":"Learn about and purchase the Astral Moon Café VIP membership directly through Ko-fi.",
    "Visitar nuestro Ko-fi":"Visit our Ko-fi", "El apoyo es completamente voluntario.":"Support is completely voluntary.",
    "✦ Síguenos por el universo digital ✦":"✦ Follow us across the digital universe ✦", "Redes Astrales":"Astral Socials",
    "Conoce nuestros próximos eventos, clips, anuncios y momentos especiales. También puedes unirte directamente a nuestra comunidad de VRChat.":"Discover our upcoming events, clips, announcements and special moments. You can also join our VRChat community directly.",
    "Servidor de Discord":"Discord Server", "Únete a la comunidad":"Join the community", "Grupo de VRChat":"VRChat Group", "Owner · Guardián y Jefe Fundador":"Owner · Guardian & Founding Leader", "Maid Lunar · Fantasmita cantora":"Lunar Maid · Little singing ghost", "Melodía errante":"Wandering Melody", "Maid Lunar · Hija de la Luna":"Lunar Maid · Daughter of the Moon", "Lágrima lunar":"Moonlit Tear", "Maid Lunar · Diosa del Mar Astral":"Lunar Maid · Goddess of the Astral Sea", "Marea de luna":"Moonlit Tide", "Maid Lunar · Alma de estrella":"Lunar Maid · Star Soul", "Estrella renacida":"Reborn Star", "Maid Lunar · Ecos sin nombre":"Lunar Maid · Nameless Echoes", "Constelación fragmentada":"Fragmented Constellation", "Maid Lunar · Rostro de Dantalion":"Lunar Maid · Face of Dantalion", "Géminis · Rostros cambiantes":"Gemini · Changing Faces",
    "☾ Hecho bajo la luz de Astral Moon Café · ✦ ·":"☾ Made beneath the light of Astral Moon Café · ✦ ·",
    "← Volver al elenco":"← Back to staff", "ROL":"ROLE", "ÁREA":"AREA", "USUARIO":"USERNAME", "CONSTELACIÓN":"CONSTELLATION", "Galería estelar":"Stellar gallery", "Foto 01":"Photo 01", "Foto 02":"Photo 02", "Foto 03":"Photo 03", "Estrella no encontrada":"Star not found", "Este perfil no está disponible.":"This profile is unavailable.", "Volver al elenco":"Back to staff", "☾ Astral Moon Café · Perfil estelar ✦":"☾ Astral Moon Café · Stellar profile ✦",
    "Señor del Cosmos":"Lord of the Cosmos", "Guardián y Jefe Fundador":"Guardian & Founding Leader", "Owner":"Owner", "Fundadora Astral":"Astral Founder", "Fundación honorífica":"Honorary founding", "Administración":"Administration", "Maids Lunares":"Lunar Maids", "Mayordomos Solares":"Solar Butlers", "Elenco Mixto":"Mixed Staff", "Maids y Mayordomos":"Maids & Butlers", "Luna regente":"Ruling Moon", "Primera chispa":"First Spark", "Estrella guía":"Guiding Star", "Eclipse":"Eclipse", "Estrella protectora":"Protective Star", "Estrella mondongal":"Mondongal Star", "Trébol de los deseos":"Clover of Wishes", "Lunas hermanas":"Sister Moons", "Bosque de los tanuki":"Tanuki Forest", "Santuario del tanuki":"Tanuki Sanctuary", "Corona del reino perdido":"Crown of the Lost Kingdom", "Singularidad errante":"Wandering Singularity", "Luz de casa":"Light of Home"
  };
  const original = new WeakMap();
  function language() { return localStorage.getItem('astral-language') === 'en' ? 'en' : 'es'; }
  function apply(lang) {
    localStorage.setItem('astral-language', lang);
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-lang]').forEach(b => { b.classList.toggle('active', b.dataset.lang === lang); b.setAttribute('aria-pressed', b.dataset.lang === lang); });
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => {
      if(!original.has(node)) original.set(node, node.nodeValue);
      const source=original.get(node), trimmed=source.trim();
      if(!trimmed) return;
      const value=lang==='en' && translations[trimmed] ? translations[trimmed] : trimmed;
      node.nodeValue=source.replace(trimmed,value);
    });
    document.title = document.body.classList.contains('profile-page')
      ? (lang === 'en' ? 'Profile | Astral Moon Café' : 'Perfil | Astral Moon Café')
      : 'Astral Moon Café';
    const description=document.querySelector('meta[name="description"]');
    if(description && !document.body.classList.contains('profile-page')) description.content=lang==='en' ? 'Meet the staff of Astral Moon Café, a stellar VRChat experience.' : 'Conoce al elenco de Astral Moon Café, una experiencia estelar en VRChat.';
    window.dispatchEvent(new CustomEvent('astral-language-change',{detail:{lang}}));
  }
  window.ASTRAL_I18N={translations,language,apply,translate(value,lang=language()){ return lang==='en' ? (translations[value]||value) : value; }};
  document.addEventListener('DOMContentLoaded',()=>{ document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>apply(b.dataset.lang))); apply(language()); });
})();
